GNUmakefile
builder/googlecompute/builder.go
builder/googlecompute/config.go
builder/googlecompute/config.hcl2spec.go
builder/googlecompute/driver_gce.go
docs-partials/builder/googlecompute/Config-not-required.mdx
docs-partials/post-processor/googlecompute-export/Config-not-required.mdx
docs-partials/post-processor/googlecompute-import/Config-not-required.mdx
docs-partials/post-processor/googlecompute-import/Config-required.mdx
docs/builders/googlecompute.mdx
post-processor/googlecompute-export/post-processor.go
post-processor/googlecompute-export/post-processor.hcl2spec.go
post-processor/googlecompute-import/post-processor.go
post-processor/googlecompute-import/post-processor.hcl2spec.go

Hello,
I need to have Packer support static access token to authenticate on Google API.
This is supported by Terraform, and I tried to implement it in Packer.
https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#access_token
It's the first time I contribute to Packer. Tell me if anything is wrong and I will fix it.
I did the following tests that is working
```shell
export PKR_VAR_access_token=$(gcloud auth application-default print-access-token)  
packer build example/build.pkr.hcl 
```
```hcl
variable "zone" {
default = "europe-west4-a"
}
variable "project_id" {
type = string
default = "fra-demo-ccc-dev-demo"
}
variable "access_token" {
type = string
sensitive = true
}
source "googlecompute" "ex" {
access_token            = var.access_token …
```

WIP: support static access-token authentication

---

builder/googlecompute/driver_gce.go

Fix Error 400: Invalid value for field 'resource.sourceDisk' #15

Fix Error 400: Invalid value for field 'resource.sourceDisk

---

builder/googlecompute/step_start_tunnel.go
builder/googlecompute/step_start_tunnel_test.go
docs/builders/googlecompute.mdx

IAP support no longer requires a service account file to work. it will work with the googlecompute account_file, GOOGLE_APPLICATION_CREDENTIALS and default credentials.
Closes #3

IAP support works with all credentials for a googlecompute builder

---

builder/googlecompute/step_import_os_login_ssh_key.go
builder/googlecompute/step_import_os_login_ssh_key_test.go

When running on a Compute Engine instance, `StepImportOSLoginSSHKey` uses the account name from the GCE instance even if a different service account is configured. This can cause Packer to authenticate to Google API using the configured service account but attempt to create an SSH key for the GCE service account, resulting in an error:
googleapi: Error 403: End user credentials must match the user specified in the request
This changes the behavior and uses the GCE service account only if there is no service account in the configuration.
Closes #5

Use user-configured Service Account for public key import when running in GCE

---

docs/builders/googlecompute.mdx

This will help GCP Packer Windows users to interact with Image builds using openssh

update ansible example

---

builder/googlecompute/config.go
builder/googlecompute/config.hcl2spec.go
builder/googlecompute/config_test.go
builder/googlecompute/driver.go
builder/googlecompute/driver_gce.go
builder/googlecompute/step_create_instance.go
docs-partials/builder/googlecompute/Config-not-required.mdx

To support Customer-managed Encryption Key for Remote VM's Boot Disk #20
End to end test [results](https://gist.github.com/wilsonfv/456af7aa688a0fe68d8705d30711753f) 
[Without disk_encryption_key](https://gist.github.com/wilsonfv/456af7aa688a0fe68d8705d30711753f#file-packer_disk_encryption_key_empty-json), default behavior will be using google-managed encryption key.
A debug log will be output similar to [below](https://gist.github.com/wilsonfv/456af7aa688a0fe68d8705d30711753f#file-packer_disk_encryption_key_empty-json-log-L56) 
> 2021/05/08 14:24:22 packer-plugin-googlecompute plugin: 2021/05/08 14:24:22 [DEBUG] using google-managed encryption key for boot disk
With disk_encryption_key [specified](https://gist.github.com/wilsonfv/456af7aa688a0fe68d8705d30711753f#file-packer_disk_encryptio …

Customer-managed Encryption Key for Remote VM's Boot Disk #20

---

builder/googlecompute/config.go
builder/googlecompute/config.hcl2spec.go
builder/googlecompute/config_test.go
builder/googlecompute/driver.go
builder/googlecompute/driver_gce.go
builder/googlecompute/driver_mock.go
builder/googlecompute/step_create_image.go
builder/googlecompute/step_create_image_test.go
docs-partials/builder/googlecompute/Config-not-required.mdx

*Allow choosing nic-type on instance creation #28*
Added a new configuration option: *image_guest_os_features*
This parameter enables one or more features for VM instances that use the image for their boot disks.
See https://cloud.google.com/compute/docs/images/create-delete-deprecate-private-images#guest-os-features
for descriptions of the supported features:
* GUEST_OS_FEATURES: GVNIC
* MULTI_IP_SUBNET
* SEV_CAPABLE
* UEFI_COMPATIBLE
* VIRTIO_SCSI_MULTIQUEUE, WINDOWS.
Closes #28

Allow choosing nic-type on instance creation #28

---

builder/googlecompute/driver.go
builder/googlecompute/driver_gce.go
builder/googlecompute/step_import_os_login_ssh_key.go
builder/googlecompute/step_import_os_login_ssh_key_test.go
post-processor/googlecompute-import/post-processor.go

Fixes: #73
Can I get some help with the `driver_mock.go`?
This change fixes a bug where the OS Login email lookup doesn't work if service account impersonation is being used. 
The `tokeninfo` function at the bottom of  `builder/googlecompute/step_import_os_login_ssh_key.go` is initialised with incorrect ClientOption and won't work if you are impersonating.
Also, `getGCEUser` is broken with service account impersonation as it uses the metadata server of the instance/pod to get the email of the identity that is impersonating and not the impersonated identity.
I have reworked it to acquire the correct Access Token from NewClientOptionGoogle and then use it to make a call to get email from https://oauth2.googleapis.com/tokeninfo
@azr @SwampDragons

Ensure OS Login API calls are using the correct Identities

---

builder/googlecompute/step_import_os_login_ssh_key.go
builder/googlecompute/step_import_os_login_ssh_key_test.go

Hello,
This Pull-Request completes https://github.com/hashicorp/packer-plugin-googlecompute/pull/13 that was merged .
Currently OSLogin do not support static token authentication, this PR fix this issue.
I tested locally and it worked.

support static access-token authentication for os-login

---

builder/googlecompute/driver_gce.go

Add rocky-linux-cloud family to the public GCE projects array.
Closes #67
```
?   	github.com/hashicorp/packer-plugin-googlecompute	[no test files]
ok  	github.com/hashicorp/packer-plugin-googlecompute/builder/googlecompute	12.064s
ok  	github.com/hashicorp/packer-plugin-googlecompute/post-processor/googlecompute-export	0.656s
ok  	github.com/hashicorp/packer-plugin-googlecompute/post-processor/googlecompute-import	0.426s
?   	github.com/hashicorp/packer-plugin-googlecompute/version	[no test files]
```

Add rocky-linux-cloud to GCE public projects

---

builder/googlecompute/driver_gce.go

Currently errors if you try to select a `fedora-cloud` image, this change will add the `fedora-cloud` project to the list of projects to be searched;
**Plugin and Packer version**
packer --version 1.7.8
hashicorp/packer-plugin-googlecompute 1.0.9
```
--> googlecompute.packer: Error getting source image for instance creation: Could not find image, fedora-cloud-35, in projects, [centos-cloud cos-cloud coreos-cloud debian-cloud rhel-cloud rhel-sap-cloud suse-cloud suse-sap-cloud suse-byos-cloud ubuntu-os-cloud windows-cloud windows-sql-cloud gce-nvme google-containers opensuse-cloud]: 16 error(s) occurred:
* googleapi: Error 404: The resource 'projects/centos-cloud/global/images/family/fedora-cloud-35' was not found, notFound
* googleapi: Error 404: The resource …
```

Add support for fedora-cloud public image project

---

builder/googlecompute/driver_gce.go

This adds the `ubuntu-os-pro-cloud` project to the list of projects in the [GetImage](https://github.com/hashicorp/packer-plugin-googlecompute/blob/main/builder/googlecompute/driver_gce.go#L257-L281) function.
If your PR resolves any open issue(s), please indicate them like this so they will be closed when your PR is merged:
Closes #87

adding ubuntu pro project

---

builder/googlecompute/driver_gce.go

Added the missing comma on line 281 causing the following error on `go build`:
```bash
builder/googlecompute/driver_gce.go:281:24: syntax error: unexpected newline, expecting comma or }
```
Should have validated before initial PR but fixed now... `go build` builds successfully.

fixed missing comma

---

builder/googlecompute/step_start_tunnel_test.go

```
jasonhatton@localhost:~/code/packer-plugin-googlecompute$ golangci-lint run
builder/googlecompute/step_start_tunnel_test.go:78:5: S1025: the argument's underlying type is a slice of bytes, should use a simple conversion instead of fmt.Sprintf (gosimple)
if fmt.Sprintf("%s", f) != expected {
```
This PR fixes this lint.

Remove unneeded Sprintf

---

builder/googlecompute/builder.go
builder/googlecompute/config.go
builder/googlecompute/driver_gce.go
builder/googlecompute/step_import_os_login_ssh_key.go
builder/googlecompute/step_wait_startup_script.go
docs-partials/post-processor/googlecompute-export/Config-not-required.mdx
docs-partials/post-processor/googlecompute-import/Config-not-required.mdx
post-processor/googlecompute-export/post-processor.go
post-processor/googlecompute-export/post-processor.hcl2spec.go
post-processor/googlecompute-import/post-processor.go
post-processor/googlecompute-import/post-processor.hcl2spec.go

I updated the code using the non-deprecated way of using Google Cloud IAM impersonation.
Despite my efforts, I've been unable to submit any relevant unit tests since this part of the code is tied to Google remote API (POST requests are performed).
I tried to invoke/create mocking objects without success.
As a result, I think that this should be tested with integration tests but it looks like nothing similar exists yet (it would probably be quite expensive to have a dedicated GCP project).
Nevertheless, I would be more than happy if someone could help me on that.
Hope my contribution will be helpful.
Closes #83

Migrate to new Google Cloud impersonation API

---

builder/googlecompute/config.go
builder/googlecompute/config.hcl2spec.go
builder/googlecompute/config_test.go
builder/googlecompute/driver.go
builder/googlecompute/driver_gce.go
builder/googlecompute/step_create_instance.go
docs-partials/builder/googlecompute/Config-not-required.mdx
docs-partials/builder/googlecompute/NodeAffinity-not-required.mdx
docs-partials/builder/googlecompute/NodeAffinity.mdx
docs-partials/builder/googlecompute/NodeAffinityConfig-not-required.mdx
docs-partials/builder/googlecompute/NodeAffinityConfig.mdx

Adds support for `node_affinity` field in googlecompute source. Example:
```hcl
node_affinity { 
key = "workload"
operator = "IN"
values = ["packer"]
}
node_affinity { 
key = "workload"
operator = "NOT_IN"
values = ["notpacker"]
}
```
I put WIP in the title because the test are giving me a panic which seems to be unrelated to my changes. However, I tested  building images with and without `node_affinity` configs. Also I'm not sure what parts get autogenerated and I shouldn't be including in my PR.
The PR also touches the `waitForState` mechanism, because if a sole-tenant node is not available the operation state becomes `DONE` but there is a precondition failed error emitted, which is flagged as a retryable error and will keep the function spinning until timeout. I'm also fine with taking …

Added support for node affinity labels

---

builder/googlecompute/driver_gce.go

Hi! I noticed that the `ml-images` project is missing from the search path of `*driverGCE.GetImageFromProjects`. Just added it.
You can verify the existence of the `ml-images` project by using the command:
```sh
▶ gcloud compute images describe-from-family common-dl-gpu-debian-10 --project=ml-images
archiveSizeBytes: '31754872320'
creationTimestamp: '2022-07-01T16:00:12.498-07:00'
description: Google, Debian 10 based Deep Learning VM with CUDA 11.3, M94, Base CUDA
11.3, Deep Learning VM Image with CUDA 11.3 preinstalled.
diskSizeGb: '50'
family: common-dl-gpu-debian-10
guestOsFeatures:
- type: VIRTIO_SCSI_MULTIQUEUE
- type: UEFI_COMPATIBLE
- type: GVNIC
id: '6830904170410853011'
kind: compute#image
labelFingerprint: 42WmSpB8rSM=
licenseCodes:
- '5638175847114525401'
- …
```

Add ml-images project to list of supported images

---

builder/googlecompute/driver_gce.go

The newer community project images such as alma-linux listed on the https://cloud.google.com/compute/docs/images
page are not yet available on the plugin.
Updating the driver project ID list to include these newly available images
Closes #119

Add support for AlamaLinux, FreeBSD, and HPC cloud images 

---

docs/builders/googlecompute.mdx

In this PR, we are going to update our official document to suggest users to use above v1.0.0, currently we left v0.0.1 that is outdated.
https://developer.hashicorp.com/packer/plugins/builders/googlecompute
v0.0.1 has a fundamental problem, this update could avoid these reports in the future.
https://github.com/hashicorp/packer-plugin-googlecompute/issues/24
The repository's README.md already recommends users to use v1.0.0, public document should be aligned with it.
https://github.com/officer/packer-plugin-googlecompute/blob/fix-document/README.md#installation

We should suggest users to use above v1.0.0

---

builder/googlecompute/config.go
builder/googlecompute/config.hcl2spec.go
builder/googlecompute/driver.go
builder/googlecompute/driver_gce.go
builder/googlecompute/step_create_instance.go
docs-partials/builder/googlecompute/Config-not-required.mdx

This PR allows us to launch a VM with nested virtualization enabled in an intermediate instance.
Closes https://github.com/hashicorp/packer-plugin-googlecompute/issues/76

Support for enabling nested virtualization on intermediate instance

---

post-processor/googlecompute-import/post-processor.go

It seems comment lines for those two config fields were inverted.
This PR fixes it.

Docs: invert comment lines for ImageSignatureDB and ImageForbiddenSignaturesDB

---

docs/builders/googlecompute.mdx

Documentation is broken
Closes #134

docs/builder: Fix reference to SSH partial

---

builder/googlecompute/step_import_os_login_ssh_key.go

The ssh username picked from the account credentials was only printed out as a message when running Packer with the `--debug' flag, making it impossible to see when running unattended builds, like in tests for example.
To remedy this issue, and see the actual username derived from the credentials, we make this message a debug log so it's always visible when running Packer with `PACKER_LOG' set.

builder: add log for ssh_username with oslogin

---

.github/workflows/acceptance-test.yml
.github/workflows/go-test-darwin.yml
.github/workflows/go-test-linux.yml
.github/workflows/go-test-windows.yml
.github/workflows/go-validate.yml
.github/workflows/jira.yml
.github/workflows/release.yml
.github/workflows/test-plugin-example.yml

Commit is the result of running HashiCorp's internal pinning tool, for all GitHub Actions workflows in the repo.
https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/
Note, this unsolicited PR is a courtesy and has not been tested before submission.  The PR should be evaluated and merged by its responsible team.

Bump all GitHub Actions and pin; avoid deprecated Node 12

---

builder/googlecompute/config.go
docs-partials/builder/googlecompute/Config-not-required.mdx

This PR will change default machine_type from `n1-standard-1` to `e2-standard-2`.
`n1-standard-1` is an old machine type and it's often not available. I confirmed with asia-northeast1-a, b, c zones.

change default machine type to e2-standard-2

---

builder/googlecompute/artifact.go
builder/googlecompute/config.go
builder/googlecompute/config.hcl2spec.go
builder/googlecompute/driver.go
builder/googlecompute/driver_gce.go
builder/googlecompute/driver_mock.go
builder/googlecompute/step_check_existing_image.go
builder/googlecompute/step_create_image.go
docs-partials/builder/googlecompute/Config-not-required.mdx
docs/builders/googlecompute.mdx

This PR resurrects and rebases [this](https://github.com/hashicorp/packer-plugin-googlecompute/pull/31) PR which creates an image_project_id configuration option (which defaults to project_id) and allows defining a different project that an image should be created in.
Closes https://github.com/hashicorp/packer-plugin-googlecompute/issues/30

feat: adds image_project_id parameter for pushing images to a different GCP project

---

builder/googlecompute/driver_gce.go

When a user specifies a `image_family_name` to get the latest version of an image to build their custom image upon, the plugin attempts to get the family specified from a static list of projects.
In this case, a user attempted to get the `fedora-coreos-stable' family, present in the `fedora-coreos-cloud` project, which was not in the default list of the GCE driver.
This commit changes this.
Closes: #191

builder: add fedora-coreos-cloud project

---

.web-docs/components/builder/googlecompute/README.md
builder/googlecompute/config.go
builder/googlecompute/testdata/extra_scratch_disk.pkr.hcl
builder/googlecompute/testdata/multiple_disks.pkr.hcl
docs-partials/builder/googlecompute/Config-not-required.mdx

Some machine types don't support local SSDs as extra block devices, so we change our acceptance tests that contain those so they use n2-* machines instead of E2-*, which don't support those block device attachments.

Fix acceptance tests with local SSDs

---

builder/googlecompute/config.go
builder/googlecompute/config_test.go
builder/googlecompute/step_create_image.go
docs-partials/lib/common/BlockDevice-not-required.mdx
lib/common/block_device.go
lib/common/block_device.hcl2spec.go

Hello! This pull request aims to allow a user to configure which disk is used when creating the GCE image from the packer instance. I've defaulted to the `disk_name`, which makes this backwards-compatible, but with this change you could now specify a `disk_name` from one of the `disk_attachment` blocks (#153).
We believe this functionality would be useful for a simpler way of taking an image, _not booting from it_, and adding extra data to it before producing a second image.
I'm open to changing the name of the setting or any other changes you may suggest. Thanks!

feat: add `image_source_disk` configuration setting

---

.web-docs/components/builder/googlecompute/README.md
builder/googlecompute/config.go
builder/googlecompute/config.hcl2spec.go
builder/googlecompute/config_test.go
builder/googlecompute/step_create_image.go
docs-partials/builder/googlecompute/Config-not-required.mdx

This PR is to add image_architecture as a config for the packer plugin. Currently this plugin only supports provisioning Image Types of X86_64 in GCP disabling the ability to create ARM based images. 
image_architecture will allow consumers of this plugin to modify the disk type being provisioned by GCE to enable ARM based packer images in GCP. 
Test and validation are included with this PR to ensure that image_architecture is set to X86_64 or ARM64, by default it will select X86_64 as its the most common. This field is also optional so leaving it blank or an empty value will serve backwards compatibility for current configs.

Image architecture config

---

builder/googlecompute/config_test.go
builder/googlecompute/step_create_instance.go
builder/googlecompute/step_create_windows_password_test.go
builder/googlecompute/step_start_tunnel_test.go
post-processor/googlecompute-import/post-processor.go

Since the ioutil package is deprecated, we update all the instances in which it is used to replace them with the preferred methods of executing those functions.

all: remove usage of ioutil

---

.web-docs/components/builder/googlecompute/README.md
docs-partials/lib/common/BlockDevice-required.mdx
lib/common/block_device.go

Hyperdisks are another volume type with high-performance compared to other persistent options.
Since they weren't supported by the builder, we add those volume types to the configuration so users can provision their volumes with those.

lib: add hyperdisk to supported volume types

---

lib/common/block_device.go

Currently, there are some zones (a very few but still) in GCP that are not conforming to that regular expression due to having two digits in the region name, before the zone suffix, i.e. europe-west10.
That PR is to allow both variations to be supported, otherwise a disk is not properly removed when an instance is being removed, and has to be deleted manually, as the script treats the value as region name not the zone.

Fix zone or region detection regex

---

.web-docs/components/builder/googlecompute/README.md
docs-partials/lib/common/BlockDevice-not-required.mdx
lib/common/block_device.go
lib/common/block_device.hcl2spec.go
lib/common/block_device_test.go

Add ability to specify a `source_image` in a `disk_attachment`.
Relevant excerpt from [GCP godocs](https://pkg.go.dev/google.golang.org/api/compute/v1#AttachedDiskInitializeParams):
```
// SourceImage: The source image to create this disk. When creating a
// new instance, one of initializeParams.sourceImage or
// initializeParams.sourceSnapshot or disks.source is required except
// for local SSD.
```

Add `source_image` to `disk_attachment`

---

builder/googlecompute/builder.go

Fix the step "start tunnel" after refactoring [849dee](https://github.com/hashicorp/packer-plugin-googlecompute/commit/849deeecfa3ea309b03fcd3f8f87a0187d328995)
Because the warning "_account_file is deprecated, please use either credentials_json or credentials_file instead_" was confusing and caused misunderstanding.

builder: fix support credentials files

---

builder/googlecompute/builder.go

From 1.1.3 to 1.1.4 the `impersonate_service_account` stopped working.
When calling `impersonate.CredentialsTokenSource` a scope must be provided, but it has been removed from the builder `&common.GCEDriverConfig`.
This PR is aiming to restore it so the service work again.
Closes #204

[BUG] Fix impersonate_service_account missing scopes

---

.github/workflows/acceptance-test.yml

Adding a job to upload failure logs as artefacts to debug better in case an acceptance test fails

Updated AccTest Github Action to upload failure logs as artifacts

---

.web-docs/components/builder/googlecompute/README.md
builder/googlecompute/config.go
builder/googlecompute/step_create_instance.go
builder/googlecompute/step_import_os_login_ssh_key.go
builder/googlecompute/step_import_os_login_ssh_key_test.go
docs-partials/builder/googlecompute/Config-not-required.mdx
lib/common/driver.go
lib/common/driver_gce.go
lib/common/driver_mock.go

This PR fixes a bug where packer did not respect the `use_os_login` param when set to false. This caused issue when osLogin was enabled at project level and one wanted to disable it at an instance level.
This PR updates the `use_os_login` param to be a trilean instead of a boolean and added a condition to set the flag to False as well.
Also added a function to fetch Project's metadata to check the status of a flag at project level, i.e. `use_os_login` status.
This was tested by enabling OsLogin at Project level and setting the `use_os_login` flag as true and false and by removing the flag.
To verify the change, when doing an SSH into the machine, the user name should be your mail in case of oslogin enabled and it should be your name in case it is disabled.
Closes #241

BUG: Fixed the UseOsLogin param to use Trilean instead

---

.web-docs/components/builder/googlecompute/README.md
builder/googlecompute/config.go
builder/googlecompute/config.hcl2spec.go
builder/googlecompute/step_create_image.go
builder/googlecompute/step_create_image_test.go
docs-partials/builder/googlecompute/Config-not-required.mdx
lib/common/driver.go
lib/common/driver_gce.go
lib/common/driver_mock.go

Adding new fields `deprecate_at`, `obsolete_at` and `delete_at` to the template to enable users to set these lifecycle properties to an Image created by Packer.
Closes #245

FEAT: Added fields to set Lifecycle Properties to an Image

---

.web-docs/components/builder/googlecompute/README.md
builder/googlecompute/config.go
builder/googlecompute/config.hcl2spec.go
builder/googlecompute/step_create_instance.go
builder/googlecompute/step_import_os_login_ssh_key.go
builder/googlecompute/step_import_os_login_ssh_key_test.go
docs-partials/builder/googlecompute/Config-not-required.mdx

Introduces an option, `oslogin_ssh_username`, to customize the SSH username used with OS Login, enabling explicit control or normalization for federated identities. Improves compatibility across authentication methods and documents the new setting for users.
The option supports the following sentinel values:
- `__auto__` [default]: Fetches the username from the OS Login profile from GCP.
- `__external__`: Adds an `ext_` to the login profile username and truncates it to 32 chars.
Closes #254

Adds configurable OS Login SSH username support
